apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: test-deploy
spec:
  replicas: 1
  selector:
    app: test-deploy
  template:
    metadata:
      labels:
        app: test-deploy
    spec:
      containers:
        - name: test-deploy
          image: test-deploy:latest
          ports:
            - containerPort: 3000
